import Head from "next/head";
import Banner from "../components/banner/Banner";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Card from "../components/card/Card";

import coffeeStoresData from "../data/coffee-stores.json";
import { Fragment } from "react";

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeStoresData,
    },
  };
}

export default function Home(props) {
  console.log("props", props);
  const handleOnBannerBtnClick = () => {
    console.log("hi banner btn");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            alt="heroImage"
            height={400}
            width={700}
            src="/static/hero-image.png"
          />
        </div>
        {props.coffeeStores.length > 0 && (
          <Fragment>
            {" "}
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore, id) => {
                return (
                  <Card
                    key={coffeeStore.id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl}
                    href={`/CoffeeStore/${coffeeStore.id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </Fragment>
        )}
      </main>
    </div>
  );
}
